### ISSUE TITLE
可以上传完整的源码吗？谢谢！

### ISSUE THREAD

**Issue by sunlewuyou** [Hzllaga/JsLoader#1]
![image](https://user-images.githubusercontent.com/19728435/78449312-e5cb9b80-76ac-11ea-8329-db82b1433a26.png)
![image](https://user-images.githubusercontent.com/19728435/78449436-efed9a00-76ac-11ea-9116-e433ff4cbd21.png)
![image](https://user-images.githubusercontent.com/19728435/78449754-05fb5a80-76ad-11ea-8dfd-857f94aa35b2.png)

问题很小白，还请您帮忙指出怎么让其能够正常编译，少了些什么，谢谢！

**Comment by Hzllaga** [comment]
第一个和第三个通过加入COM组件TaskSchedulerClass Type Library可以解决

第二个你必须新增Resource到项目里面，或是直接把二进制文件转成Byte Array直接写出，再或者其实你可以不用写出exe，你可以通过对代码的修改直接新建一个带参数的计划任务，比如cscript.exe eval.js

**Comment by sunlewuyou** [comment]
感谢，我先学习一下，谢谢！

**Comment by sunlewuyou** [comment]
博主，您这域名的证书也该重新续一下了吧。
![image](https://user-images.githubusercontent.com/19728435/78467472-c5005600-773f-11ea-8417-1b7608eb3322.png)

**Comment by Hzllaga** [comment]
感谢，采用多地部署，忘记续签那台服务器了，已修正。

**Comment by sunlewuyou** [comment]
![image](https://user-images.githubusercontent.com/19728435/78499297-63ada680-7782-11ea-96d0-e52656964042.png)
博主您测试的时候360是不会拦截的吗?

**Comment by Hzllaga** [comment]
是的呢，360是最容易处理的杀毒，你这个情况估计是我那个js入特征码了，刚刚看了下国外杀毒好多都会检测了。

360的绕过方法也很简单，把文件格式换成其他的，比如tmp或cache就直接绕过了。

**Comment by sunlewuyou** [comment]
![image](https://user-images.githubusercontent.com/19728435/78499687-c3a54c80-7784-11ea-9523-0d4270e9c846.png)
360是最新版本和最新病毒库，这是行为特征检测吧

**Comment by sunlewuyou** [comment]
![image](https://user-images.githubusercontent.com/19728435/78499760-1b43b800-7785-11ea-8507-45cffdd5104f.png)
js也已经混淆

**Comment by sunlewuyou** [comment]
下载的时候就被拦截，那新建计划任务的时候那八九不离十也会被拦截吧？博主您可以升级最新的360杀毒、卫士套装进行测试一下吗？咱这踩坑填坑速度实在不如博主。

**Comment by Hzllaga** [comment]
额。。不出意外的话我这是最新版的吧。
![圖片](https://user-images.githubusercontent.com/40329078/78500285-13d1de00-7788-11ea-8bf9-b73ca80fed3d.png)

确实是能直接上线的

![圖片](https://user-images.githubusercontent.com/40329078/78500300-2a783500-7788-11ea-9e82-ef364aeb96c2.png)

**Comment by sunlewuyou** [comment]
![image](https://user-images.githubusercontent.com/19728435/78500518-8becd380-7789-11ea-9ead-7072f6fd0c45.png)
卧槽！你的程序版本比我还要高居然都检测不到，这360搞区别对待呀？！

**Comment by sunlewuyou** [comment]
难道你的是beta版本的bug??

**Comment by Hzllaga** [comment]
> 360的绕过方法也很简单，把文件格式换成其他的，比如tmp或cache就直接绕过了。

我这句话说的是改本地的js文件，不是远程的，你试下应该就绕过了。

**Comment by sunlewuyou** [comment]
![image](https://user-images.githubusercontent.com/19728435/78500823-492bfb00-778b-11ea-9910-e9ae0077b6be.png)
看来此法已只有部分情况可以了。

**Comment by sunlewuyou** [comment]
![image](https://user-images.githubusercontent.com/19728435/78501736-99a55780-778f-11ea-96d2-bcc5ca955001.png)
![image](https://user-images.githubusercontent.com/19728435/78501747-b2157200-778f-11ea-98a3-a976f0469753.png)

**Comment by Hzllaga** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/19728435/78500823-492bfb00-778b-11ea-9910-e9ae0077b6be.png)
> 看来此法已只有部分情况可以了。

大哥，我说的是改文件格式(xx.js => xx.cache)，你这肯定被拦截啊。。。

**Comment by Hzllaga** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/19728435/78501736-99a55780-778f-11ea-96d2-bcc5ca955001.png)
> ![image](https://user-images.githubusercontent.com/19728435/78501747-b2157200-778f-11ea-98a3-a976f0469753.png)

是的，添加现有文件test.exe

**Comment by sunlewuyou** [comment]
![image](https://user-images.githubusercontent.com/19728435/78503527-b9417d80-7799-11ea-8481-9c711a16baf9.png)
![image](https://user-images.githubusercontent.com/19728435/78503606-4be21c80-779a-11ea-8276-83e5ac00f15f.png)

**Comment by sunlewuyou** [comment]
![image](https://user-images.githubusercontent.com/19728435/78503713-f0645e80-779a-11ea-8294-24ebeb3a3612.png)

**Comment by Hzllaga** [comment]
> ![image](https://user-images.githubusercontent.com/19728435/78503527-b9417d80-7799-11ea-8481-9c711a16baf9.png)

可以，用ILMerge
> ![image](https://user-images.githubusercontent.com/19728435/78503606-4be21c80-779a-11ea-8276-83e5ac00f15f.png)

test.exe是释放js用的，可有可无，当初就是写着多提供一种方法而已。

**Comment by Hzllaga** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/19728435/78503713-f0645e80-779a-11ea-8294-24ebeb3a3612.png)

显然已经绕过了，你现在被拦截的是因为你msf的payload尝试把自己进程迁移到svchost.exe上，你可以选择不要自动注入就不会被拦截，前段时间开始360就全面拦截远程注入了，至于绕过方法我就不提供了。

**Comment by Hzllaga** [comment]
你的问题应该都解决了，这个issue我就close了，有其他问题再开。

**Comment by sunlewuyou** [comment]
原来如此，感谢，又学到知识了！最后问下截图中那个dll文件该怎么和程序整合到一起呢？

**Comment by Hzllaga** [comment]
请参考：[ILMerge](https://github.com/dotnet/ILMerge)

**Comment by sunlewuyou** [comment]
好的👌您也早点休息！
