### ISSUE TITLE
有的电脑没有安装.net框架或版本不够，请问应该怎么样最好呢?

### ISSUE THREAD

**Issue by 9tail123** [Hzllaga/JsLoader#3]
之前的想法是上线自动就运行脚本添加自启，但如果目标之前没有安装.net框架，效果就会不太好，请问大佬能否指教一下，谢谢

**Comment by Hzllaga** [comment]
如果不要透过.net可以使用C语言直接操作，windows我没记错的话应该是都自带.net框架的，这个项目的例子不支持低版本windows，可以用[TaskScheduler](https://github.com/dahall/TaskScheduler)替代，目前用了几个月了基本上还没遇过自启加失败的。

**Comment by 9tail123** [comment]
我现在也是用的TaskScheduler，基于2.0，但win10默认装的都是4.x，一些客户端会缺少环境。请问这样考虑的是否有错误的地方?

**Comment by Hzllaga** [comment]
看你这个需求应该是钓鱼用的吧，我一般都是把2和4的版本都丢进去内存运行，总有一个会成功🤣

**Comment by 9tail123** [comment]
我今天也考虑到制作两个版本的同时运行，不过这样子也就必定会有一个提示缺少框架的，有点不完美。所以来问下有没有更好的方法，哈哈

**Comment by 9tail123** [comment]
大佬方便留联系方式后续交流吗，这方面问题想请教一下

**Comment by Hzllaga** [comment]
坚持用.net的话最简单的方式就是判断当前系统装了什么版本在执行对应的程序就行。
tg同id，可以直接联系。

**Comment by 9tail123** [comment]
好的，我继续尝试一下，感谢大佬指教
